name: vChat
version: ${version}
main: me.marti.vchat.VChat
api-version: 1.21
authors: [mtynnn]
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  vchat:
    description: Main command for vChat
    usage: /vchat help
  showitem:
    description: Show your item in chat
    usage: /showitem
    permission: vchat.showitem
  msg:
    description: Send a private message
    usage: /msg <player> <message>
    aliases: [w, tell, whisper, dm]
    permission: vchat.msg
  reply:
    description: Reply to the last message
    usage: /reply <message>
    aliases: [r]
    permission: vchat.reply
  togglemsg:
    description: Toggle private messages
    usage: /togglemsg
    aliases: [tmsg]
    permission: vchat.togglemsg
  spychat:
    description: Toggle social spy
    usage: /spychat
    aliases: [spy]
    permission: vchat.spychat
  togglechat:
    description: Toggle YOUR view of global chat
    usage: /togglechat
    permission: vchat.togglechat
  mutechat:
    description: Mute global chat for everyone
    usage: /mutechat
    aliases: [globalmute]
    permission: vchat.mutechat
  ignore:
    description: Toggle ignoring a player
    usage: /ignore <player>
    permission: vchat.ignore
  togglementions:
    description: Alternar menciones
    usage: /togglementions
    permission: vchat.togglementions

permissions:
  vchat.admin:
    description: Permiso de administrador completo.
    default: op
  vchat.reload:
    description: Permite recargar la configuración.
    default: op
  vchat.notify:
    description: Permite ver comandos de notificación.
    default: op
  vchat.notify.auto:
    description: Recibe notificaciones automáticamente al entrar.
    default: op
  vchat.showitem:
    description: Permite usar /showitem.
    default: true
  vchat.msg:
    description: Permite enviar mensajes privados.
    default: true
  vchat.reply:
    description: Permite responder mensajes privados.
    default: true
  vchat.togglemsg:
    description: Permite activar/desactivar mensajes privados.
    default: true
  vchat.spychat:
    description: Permite ver mensajes privados ajenos.
    default: op
  vchat.bypass.msg:
    description: Permite enviar mensajes a quien los tenga desactivados.
    default: op
  vchat.togglechat:
    description: Permite activar/desactivar el chat para uno mismo.
    default: true
  vchat.mutechat:
    description: Permite silenciar el chat global para todos.
    default: op
  vchat.bypass.togglechat:
    description: Permite hablar cuando el chat está desactivado.
    default: op
  vchat.ignore:
    description: Permite ignorar jugadores.
    default: true
  vchat.bypass.ignore:
    description: Evita ser ignorado.
    default: op

  # Bypass Filters
  vchat.bypass.spam:
    description: Bypass del filtro de spam.
    default: op
  vchat.bypass.caps:
    description: Bypass del filtro de mayúsculas.
    default: op
  vchat.bypass.ads:
    description: Bypass del filtro de publicidad.
    default: op
  vchat.bypass.profanity:
    description: Bypass del filtro de groserías.
    default: op
  vchat.bypass.all:
    description: Bypass de todos los filtros.
    default: op
    children:
      vchat.bypass.spam: true
      vchat.bypass.caps: true
      vchat.bypass.ads: true
      vchat.bypass.profanity: true

  # Formatting Permissions
  vchat.format.color.basic:
    description: Permite usar colores básicos (&a-f, 0-9) y tags MiniMessage básicos (<red>).
    default: op
  vchat.format.color.hex:
    description: Permite usar colores HEX (&#, <#>) y gradientes.
    default: op
  vchat.format.style.basic:
    description: Permite estilos básicos (&l,n,o,m) y tags (<bold>, etc).
    default: op
  vchat.format.style.magic:
    description: Permite estilo mágico (&k, <obfuscated>).
    default: op

  # Mention Permission
  vchat.mention:
    description: Permite mencionar a otros jugadores.
    default: true
  vchat.togglementions:
    description: Permite activar/desactivar menciones.
    default: true
